project:
  type: website
  output-dir: docs

resources:
  - robots.txt
metadata-files: [assets/misc/metadata.yml]

website:
  title: "Shunkei Kakimoto"
  favicon: assets/image/favicon.ico
  # favicon: assets/image/favicon.png
  open-graph: true
  page-footer: "© 2025 Shunkei Kakimoto"
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: G-Z70HE9F4JL
  navbar:
    left:
      - href: index.qmd
        text: "About"
      - href: research.qmd
        text: "Research & Talks"
      - href: teaching.qmd
        text: "Teaching"
      - href: blog.qmd
        text: "Blog"
      - href: CV.qmd
        text: "CV"
    right:
      - icon: github
        href: https://github.com/Shunkei3

site-metadata:
  description: "柿元俊慧 (Shunkei Kakimoto, かきもと しゅんけい) - ミネソタ大学 応用経済学 博士課程"
  keywords: ["柿元俊慧", "ミネソタ大学", "カキモトシュンケイ", "かきもと しゅんけい", "Shunkei Kakimoto"]

    
format:
  html:
    page-layout: full
    fontsize: 20px
    theme: assets/css/theme.scss
    mainfont: Roboto
    toc: true

