project:
  type: website
  output-dir: docs

resources:
  - robots.txt
metadata-files: [assets/misc/metadata.yml]

website:
  title: "Shunkei Kakimoto"
  favicon: assets/image/favicon.ico
  open-graph: true
  page-footer: "© 2025 Shunkei Kakimoto"
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: G-Z70HE9F4JL
  site-url: "https://shunkei3.github.io"
  site-path: "/"
  search: true
  navbar:
    left:
      - href: index.qmd
        icon: person-circle
        text: "About"
      - href: research.qmd
        icon: journals
        text: "Research & Talks"
      - href: teaching.qmd
        icon: mortarboard
        text: "Teaching"
      - href: posts/index.qmd
        icon: pencil-square
        text: "Posts"
      - href: CV.qmd
        icon: file-earmark-check
        text: "CV"
    right:
      - icon: github
        href: https://github.com/Shunkei3/Shunkei3.github.io

site-metadata:
  description: "柿元俊慧 (Shunkei Kakimoto, かきもと しゅんけい) - ミネソタ大学 応用経済学 博士課程"
  keywords: ["柿元俊慧", "ミネソタ大学", "カキモトシュンケイ", "かきもと しゅんけい", "Shunkei Kakimoto"]

    
format:
  html:
    page-layout: full
    fontsize: 18px
    theme: assets/css/theme.scss
    # mainfont: Work Sans
    toc: true

